/**
 * Differential test against the Go library.
 *
 * `corpus/expected.json` is generated by running `corpus/cases.json` through
 * the *Go* implementation (see scripts/gen-corpus-expectations.go). Every
 * case here therefore asserts that this port agrees with Go, across the
 * option surface that the golden files do not reach.
 */

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { Converter, type ConvertOptions } from "../src/converter/converter.js";
import { newBasePlugin } from "../src/plugins/base/index.js";
import { newCommonmarkPlugin } from "../src/plugins/commonmark/index.js";
import { newStrikethroughPlugin } from "../src/plugins/strikethrough/index.js";
import { newTablePlugin } from "../src/plugins/table/index.js";

interface Expectation {
  config: string;
  html: string;
  expected: string;
}

const corpusDir = join(dirname(fileURLToPath(import.meta.url)), "corpus");
const expectations: Expectation[] = JSON.parse(
  readFileSync(join(corpusDir, "expected.json"), "utf8"),
);

function build(config: string): [Converter, ConvertOptions] {
  const withTable = (options = {}): Converter =>
    new Converter({
      plugins: [newBasePlugin(), newCommonmarkPlugin(), newTablePlugin(options)],
    });

  switch (config) {
    case "default":
      return [new Converter({ plugins: [newBasePlugin(), newCommonmarkPlugin()] }), {}];

    case "setext":
      return [
        new Converter({
          plugins: [newBasePlugin(), newCommonmarkPlugin({ headingStyle: "setext" })],
        }),
        {},
      ];

    case "underscore":
      return [
        new Converter({
          plugins: [
            newBasePlugin(),
            newCommonmarkPlugin({ emDelimiter: "_", strongDelimiter: "__" }),
          ],
        }),
        {},
      ];

    case "plus-bullet":
      return [
        new Converter({
          plugins: [newBasePlugin(), newCommonmarkPlugin({ bulletListMarker: "+" })],
        }),
        {},
      ];

    case "tilde-fence":
      return [
        new Converter({
          plugins: [newBasePlugin(), newCommonmarkPlugin({ codeBlockFence: "~~~" })],
        }),
        {},
      ];

    case "no-escape":
      return [
        new Converter({
          plugins: [newBasePlugin(), newCommonmarkPlugin()],
          escapeMode: "disabled",
        }),
        {},
      ];

    case "domain":
      return [
        new Converter({ plugins: [newBasePlugin(), newCommonmarkPlugin()] }),
        { domain: "https://example.com" },
      ];

    case "link-skip":
      return [
        new Converter({
          plugins: [
            newBasePlugin(),
            newCommonmarkPlugin({
              linkEmptyHrefBehavior: "skip",
              linkEmptyContentBehavior: "skip",
            }),
          ],
        }),
        {},
      ];

    case "no-list-comment":
      return [
        new Converter({
          plugins: [newBasePlugin(), newCommonmarkPlugin({ listEndComment: false })],
        }),
        {},
      ];

    case "strike":
      return [
        new Converter({
          plugins: [newBasePlugin(), newCommonmarkPlugin(), newStrikethroughPlugin()],
        }),
        {},
      ];

    case "table":
      return [withTable(), {}];
    case "table-minimal":
      return [withTable({ cellPaddingBehavior: "minimal" }), {}];
    case "table-none":
      return [withTable({ cellPaddingBehavior: "none" }), {}];
    case "table-mirror":
      return [withTable({ spanCellBehavior: "mirror" }), {}];
    case "table-preserve":
      return [withTable({ newlineBehavior: "preserve" }), {}];
    case "table-skip-empty":
      return [withTable({ skipEmptyRows: true }), {}];
    case "table-promote":
      return [withTable({ headerPromotion: true }), {}];
    case "table-presentation":
      return [withTable({ presentationTables: true }), {}];

    default:
      throw new Error(`unknown config: ${config}`);
  }
}

describe("matches the Go implementation", () => {
  it("has expectations to check", () => {
    expect(expectations.length).toBeGreaterThan(50);
  });

  const byConfig = new Map<string, Expectation[]>();
  for (const e of expectations) {
    const list = byConfig.get(e.config) ?? [];
    list.push(e);
    byConfig.set(e.config, list);
  }

  for (const [config, cases] of byConfig) {
    describe(config, () => {
      for (const [i, testCase] of cases.entries()) {
        it(`#${i + 1} ${JSON.stringify(testCase.html.slice(0, 60))}`, () => {
          const [conv, options] = build(config);
          expect(conv.convertString(testCase.html, options)).toBe(testCase.expected);
        });
      }
    });
  }
});
