import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { stringWidth } from "../src/internal/width.js";
import { cellDisplayWidth } from "../src/plugins/table/utils.js";

const corpusDir = join(dirname(fileURLToPath(import.meta.url)), "corpus");

describe("stringWidth", () => {
  it("measures the documented cases", () => {
    expect(stringWidth("abc")).toBe(3);
    expect(stringWidth("名稱")).toBe(4);
    expect(stringWidth("é")).toBe(1);
    expect(stringWidth("\u{1F60A}")).toBe(2);
    expect(stringWidth("\u{1F468}‍\u{1F469}‍\u{1F467}‍\u{1F466}")).toBe(2);
    expect(stringWidth("")).toBe(0);
  });

  it("is what the table plugin uses for padding", () => {
    expect(cellDisplayWidth("名稱")).toBe(4);
    expect(cellDisplayWidth("abc")).toBe(3);
  });

  // Generated by running the same strings through `uniseg.StringWidth` in Go.
  // See scripts/gen-width-corpus.go.
  describe("agrees with Go's uniseg", () => {
    const rows: Array<{ s: string; w: number }> = JSON.parse(
      readFileSync(join(corpusDir, "widths.json"), "utf8"),
    );

    it("has samples to check", () => {
      expect(rows.length).toBeGreaterThan(1000);
    });

    it("matches every sample", () => {
      const mismatches: Array<{ s: string; want: number; got: number }> = [];
      for (const { s, w } of rows) {
        const got = stringWidth(s);
        if (got !== w) {
          mismatches.push({ s, want: w, got });
        }
      }
      expect(mismatches).toEqual([]);
    });
  });
});
